---
title: Remove 'Cast to device' from Context Menu
description: Removes 'Cast to device' from Context Menu
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Shell Extensions\Blocked'
    value: '{7AD84985-87B4-4a16-BE58-8B72A5B390F7}'
    data: ''
    type: REG_SZ
