---
title: Remove Bitmap Image from 'New' Context Menu
description: Removes bitmap image from the 'New' context menu
privilege: TrustedInstaller
actions:
  - !registryKey: {path: 'HKCR\.bmp\ShellNew'}
  - !run:
    exe: 'powershell.exe'
    args: '-NoP -EP Unrestricted & "REMOVEBITMAP.ps1"'
    exeDir: true
    wait: true
