---
title: Defaults
description: Run default AtlasFolder scripts
onUpgrade: false
actions:
  - !writeStatus: {status: 'Applying default Atlas Folder settings'}
  - !cmd:
    command: 'reg import .\DEFAULT.reg'
    exeDir: true
    wait: true
    runas: currentUserElevated
