---
title: Configure Content Delivery Manager
description: Configures Content Delivery Manager not to download any applications such as Disney+ and disables suggested content (tips/tricks/facts/suggestions/ads) for QoL and privacy
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'ContentDeliveryAllowed'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'OemPreInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'PreInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'PreInstalledAppsEverEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SilentInstalledAppsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-310093Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338393Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-353694Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-353696Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338387Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'RotatingLockScreenOverlayEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338388Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SystemPaneSuggestionsEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SubscribedContent-338389Enabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ContentDeliveryManager'
    value: 'SoftLandingEnabled'
    data: '0'
    type: REG_DWORD
