---
title: Disable Reserved Storage
description: Disables reserved storage for Windows Updates to have more storage space
actions:
  - !run: {exe: 'DISM.exe', args: '/Online /Set-ReservedStorageState /State:Disabled', weight: 30, ignoreErrors: true}
