---
title: Disable Automatic Folder Discovery
description: Improves performance in File Explorer by not automatically determining the folder 'type' (such as pictures) for each folder's content.
actions:
    # Use this instead once AME fixes hives issue
  # - !registryValue:
  #   path: 'HKU\DefaultUser\Software\Classes\Local Settings\Software\Microsoft\Windows\Shell\Bags\AllFolders\Shell'
  #   value: 'FolderType'
  #   data: 'NotSpecified'
  #   type: REG_SZ
  - !cmd:
    command: '"AtlasDesktop\4. Interface Tweaks\File Explorer Customization\Automatic Folder Discovery\Disable Automatic Folder Discovery (default).cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated