---
title: Disable Fault Tolerant Heap (FTH)
description: FTH is a feature in Windows 7+ that applies mitigations (non-CPU related) to applications that repeatedly crash to prevent further crashes, but when the FTH is active for a certain application, there's a performance hit.
privilege: TrustedInstaller
actions:
    # https://devblogs.microsoft.com/oldnewthing/20120125-00/?p=8463
    # Document listed as only affected in Windows 7, is also in 7+
    # https://docs.microsoft.com/en-us/windows/win32/win7appqual/fault-tolerant-heap
    # https://www.3dcadworld.com/windows-7-fault-tolerant-heap-prevents-crashing/

  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\FTH'
    value: 'Enabled'
    data: '0'
    type: REG_DWORD
    # Reset FTH entries
  - !run: {exe: 'rundll32.exe', args: 'fthsvc.dll,FthSysprepSpecialize'}
