---
title: Extend Icon Cache
description: Extends the icon cache to 4MB for better responsiveness
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer'
    value: 'Max Cached Icons'
    data: '4096'
    type: REG_SZ
