---
title: Disable Menu Hover Delay
description: Makes hovering over sub-menus in menus instant, instead of having a slight delay on hover
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Control Panel\Desktop'
    value: 'MenuShowDelay'
    data: '0'
    type: REG_SZ
    
    
