---
title: Disable Shared Experiences
description: Disables 'Shared Experiences', which is a way of sharing items between advices for privacy and QoL
actions:
  # https://www.elevenforum.com/t/turn-on-or-off-nearby-sharing-in-windows-11.2644/
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP\SettingsPage'
    value: 'BluetoothLastDisabledNearShare'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP'
    value: 'NearShareChannelUserAuthzPolicy'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\CDP'
    value: 'CdpSessionUserAuthzPolicy'
    data: '1'
    type: REG_DWORD
