---
title: Restore Old Context Menu
description: Restores the old context menu in Windows 11
builds: [ '>=22000' ]
actions:
    # Use this instead once AME fixes hives issue
  # - !registryValue:
  #   path: 'HKCU\Software\Classes\CLSID\{86ca1aa0-34aa-4e8b-a509-50c905bae2a2}\InprocServer32'
  #   value: ''
  #   data: ''
  #   type: REG_SZ
  - !cmd:
    command: '"AtlasDesktop\4. Interface Tweaks\Context Menus\Windows 11\Old Context Menu (default).cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated