---
title: Disable Windows Chat
description: Disables Windows Chat as it's not commonly used
actions:
    # Windows 10
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Connect'
    data: ''
    type: REG_NONE
    builds: [ '!>=22000' ]
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Location'
    data: ''
    type: REG_NONE
    builds: [ '!>=22000' ]
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.ScreenClipping'
    data: ''
    type: REG_NONE
    builds: [ '!>=22000' ]
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\QuickActionsStateCapture'
    value: 'Toggles'
    data: 'Toggles,Microsoft.QuickAction.BlueLightReduction:false,Microsoft.QuickAction.AllSettings:false,Microsoft.QuickAction.Project:false'
    type: REG_SZ
    builds: [ '!>=22000' ]

    # Windows 11
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.Cast'
    data: ''
    type: REG_NONE
    builds: [ '>=22000' ]
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\Unpinned'
    value: 'Microsoft.QuickAction.NearShare'
    data: ''
    type: REG_NONE
    builds: [ '>=22000' ]
  - !registryValue:
    path: 'HKCU\Control Panel\Quick Actions\Control Center\QuickActionsStateCapture'
    value: 'Toggles'
    data: 'Toggles,Microsoft.QuickAction.BlueLightReduction:false,Microsoft.QuickAction.Accessibility:false,Microsoft.QuickAction.ProjectL2:false'
    type: REG_SZ
    builds: [ '>=22000' ]
