---
title: Modify Client.CBS
description: Modifies components related to Client.CBS, the miscellaneous system package in Windows 10+
privilege: TrustedInstaller
actions:
  - !powerShell:
    command: '.\CLIENTCBS.ps1'
    exeDir: true
    wait: true
