---
title: Runs NGEN on PowerShell libraries
description: Optimizes PowerShell startup time by compiling the .NET libraries
privilege: TrustedInstaller
actions:
  - !powerShell:
    command: '.\NGEN.ps1'
    exeDir: true
