---
title: Disable Devices
description: Disables devices that users would not typically need to reduce any potential system resources usage in the background
privilege: TrustedInstaller
actions:
  - !powerShell: {command: 'Disable-NetAdapterBinding -Name "*" -ComponentID ms_msclient, ms_server, ms_lldp, ms_lltdio, ms_rspndr'}
  - !powerShell:
    command: '.\DISABLEPNP.ps1'
    exeDir: true
