---
title: Set File Associations
description: Sets file associations for the user-selected web browser and other apps like the Windows Photo Viewer
privilege: TrustedInstaller
actions:
  - !run:
    exe: 'FILEASSOC.cmd'
    exeDir: true
    wait: true
    option: '!uninstall-edge'
  - !run:
    exe: 'FILEASSOC.cmd'
    args: '"Brave"'
    option: 'browser-brave'
    exeDir: true
    wait: true
  - !run:
    exe: 'FILEASSOC.cmd'
    args: '"LibreWolf"'
    option: 'browser-librewolf'
    exeDir: true
    wait: true
  - !run:
    exe: 'FILEASSOC.cmd'
    args: '"Google Chrome"'
    option: 'browser-chrome'
    exeDir: true
    wait: true
