---
title: Status in AME Wizard for the Networking Category
description: Displays a status in AME Wizard for a specified category
privilege: TrustedInstaller
actions:
  - !writeStatus: {status: 'Running networking tweaks'}