---
title: Disable AutoRun/AutoPlay
description: Disables AutoRun/AutoPlay for the optimal security and usability/QoL
privilege: TrustedInstaller
actions:
    # Disable USB autorun/play
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoAutorun'
    data: '1'
    type: REG_DWORD
    # Disable Autoplay and Autorun
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\AutoplayHandlers'
    value: 'DisableAutoplay'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoDriveTypeAutoRun'
    data: '255'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\Explorer'
    value: 'NoAutorun'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'NoAutoplayfornonVolume'
    data: '1'
    type: REG_DWORD