---
title: Adds Batch Scripts to 'New' Context Menu
description: Adds batch scripts (.bat) to 'New' context menu
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKCR\.bat\ShellNew'
    value: 'ItemName'
    data: '@C:\Windows\System32\acppage.dll,-6002'
    type: REG_EXPAND_SZ
  - !registryValue:
    path: 'HKCR\.bat\ShellNew'
    value: 'NullFile'
    data: ''
    type: REG_SZ
