---
title: Add PowerShell Script to 'New' Context Menu
description: Adds PowerShell script (.ps1) to 'New' context menu
actions:
  - !registryValue:
    path: 'HKCR\.ps1'
    value: ''
    data: 'Microsoft.PowerShellScript.1'
    type: REG_SZ
  - !registryValue:
    path: 'HKCR\.ps1\ShellNew'
    value: 'NullFile'
    data: ''
    type: REG_SZ
  - !registryValue:
    path: 'HKCR\Microsoft.PowerShellScript.1'
    value: ''
    data: 'Windows PowerShell Script'
    type: REG_SZ
  - !registryValue:
    path: 'HKCR\Microsoft.PowerShellScript.1'
    value: 'FriendlyTypeName'
    data: 'Windows PowerShell Script'
    type: REG_SZ
