---
title: Disable Use Check Boxes to Select Items
description: Disables check boxes in File Explorer to select items for QoL
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'AutoCheckSelect'
    data: '0'
    type: REG_DWORD
    
    
