---
title: Remove Shortcut Text
description: Removes '- Shortcut' text appended onto the end of shortcuts for QoL
actions:
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\NamingTemplates'
    value: 'ShortcutNameTemplate'
    data: '"%s.lnk"'
    type: REG_SZ
    
    
