---
title: Disable Recall Snapshots
description: Disables snapshots of Recall (24H2+)
builds: [ '>=22000' ]
actions:
  - !cmd:
    command: 'reg import "AtlasDesktop\3. General Configuration\AI Features\Recall\Disable Recall Support (default).reg"'
    exeDir: true
    wait: true
