---
title: Disable Performance Track
description: Disables tracking of responsiveness events for privacy
actions:
    # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.PerformancePerftrack::WdiScenarioExecutionPolicy
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WDI\{9c5a40da-b965-4fc3-8781-88dd50a6299d}'
    value: 'ScenarioExecutionEnabled'
    data: '0'
    type: REG_DWORD
