---
title: Disable Online Speech Recognition
description: Disables online speech recognition for privacy purposes
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy'
    value: 'HasAccepted'
    data: '0'
    type: REG_DWORD
    
    
    # Allow user to enable it in case they need to
  # - !registryValue:
  #   path: 'HKLM\SOFTWARE\Policies\Microsoft\InputPersonalization'
  #   value: 'AllowInputPersonalization'
  #   data: '0'
  #   type: REG_DWORD
