---
title: Do Not Use Diagnostic Data For Tailored Experiences
description: Prevents Windows from using diagnostic data for tailored experiences for privacy, also labeled as "Let Microsoft provide more tailored experiences with relevant tips and recommendations by using your diagnostic data"
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Windows\CurrentVersion\Privacy'
    value: 'TailoredExperiencesWithDiagnosticDataEnabled'
    data: '0'
    type: REG_DWORD
    
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Policies\Microsoft\Windows\CloudContent'
    value: 'DisableTailoredExperiencesWithDiagnosticData'
    data: '1'
    type: REG_DWORD
    