---
title: Configure Search on the Taskbar
description: Configures search for the optimal usability and privacy, such as disabling online features to make it more minimal and snappy
actions:
    # Configure search permissions
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'
    value: 'BingSearchEnabled'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsAADCloudSearchEnabled'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsDeviceSearchHistoryEnabled'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsMSACloudSearchEnabled'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'SafeSearchMode'
    data: '0'
    type: REG_DWORD
    
    

    # Policies
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'ConnectedSearchUseWeb'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'DisableWebSearch'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'AllowSearchToUseLocation'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'EnableDynamicContentInWSB'
    data: '0'
    type: REG_DWORD

    # Disable online search and don't include web results from Bing
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'DisableSearchBoxSuggestions'
    data: '1'
    type: REG_DWORD
    
    
    # Set search as icon on taskbar
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'
    value: 'SearchboxTaskbarMode'
    data: '1'
    type: REG_DWORD
    
    # Fallback for OOBE as it doesn't seem to work
  - !powerShell:
    command: 'reg add "HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Search" /t REG_DWORD /v "SearchboxTaskbarMode" /d 1 /f > nul'
    exeDir: true
    oobe: only
    
