---
title: Configure Windows Ink Workspace
description: Configures the Windows Ink Workspace to not be in the way, and have the best usability and privacy
actions:
  - !registryValue:
    path: 'HKU\.DEFAULT\SOFTWARE\Microsoft\Windows\CurrentVersion\PenWorkspace'
    value: 'PenWorkspaceAppSuggestionsEnabled'
    data: '0'
    type: REG_DWORD
    
    
