---
title: Disable Spell Checking
description: Disables spell checking for QoL
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'
    value: 'EnableAutocorrection'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'
    value: 'EnableDoubleTapSpace'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'
    value: 'EnablePredictionSpaceInsertion'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'
    value: 'EnableSpellchecking'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\TabletTip\1.7'
    value: 'EnableTextPrediction'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
