---
title: Disable Microsoft Consumer Experiences
description: Disables Microsoft consumer experiences (annoying tips and recommendations) for Enterprise and Education SKUs
privilege: TrustedInstaller
actions:
  # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.CloudContent::DisableWindowsConsumerFeatures
  - !registryValue:
    path: 'HKLM\Software\Policies\Microsoft\Windows\CloudContent'
    value: 'DisableWindowsConsumerFeatures'
    data: '1'
    type: REG_DWORD
