---
title: Disable 'Notify About USB Issues'
description: Disables 'Notify me if there are issues connecting to USB devices' as this is prone to false positives, for QoL
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Shell\USB'
    value: 'NotifyOnUsbErrors'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\SOFTWARE\Microsoft\Shell\USB'
    value: 'NotifyOnWeakCharger'
    data: '0'
    type: REG_DWORD
    
    
