---
title: Disable Dynamic Lighting
description: Disables Dynamic Lighting by default
builds: [ '>=22000' ]
actions:
  - !registryValue:
    path: 'HKCU\Software\Microsoft\Lighting'
    value: 'AmbientLightingEnabled'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
