---
title: Disable Touch Visual Feedback
description: Disables touch visual feedback for QoL
actions:
  - !registryValue:
    path: 'HKCU\Control Panel\Cursors'
    value: 'GestureVisualization'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
  - !registryValue:
    path: 'HKCU\Control Panel\Cursors'
    value: 'ContactVisualization'
    data: '0'
    type: REG_DWORD
    scope: defaultUser
    
