---
title: Disable Screen Capture Hotkey
description: Disables using the print screen key to open Screen Capture when Snipping Tool is removed
actions:
  - !registryValue:
    path: 'HKU\.DEFAULT\Control Panel\Keyboard'
    value: 'PrintScreenKeyForSnippingEnabled'
    data: '0'
    type: REG_DWORD
    
    
