---
title: Disable UAC Secure Desktop
description: Disables switching to the Secure Desktop when prompting for elevation. An application would need admin privileges to control the mouse and keyboard to accept the UAC prompt anyways. As a note, UAC is not designed to save you from malware, UAC can easily be bypassed on admin accounts (e.g. check GitHub)
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System'
    value: 'PromptOnSecureDesktop'
    data: '0'
    type: REG_DWORD
