---
title: Configure Visual Effects
description: Configures the visual effects in Windows for the optimal responsiveness, performance and QoL
actions:
  - !registryValue:
    path: 'HKU\DefaultUser\Control Panel\Desktop'
    value: 'FontSmoothing'
    data: '2'
    type: REG_SZ
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\Control Panel\Desktop'
    value: 'UserPreferencesMask'
    data: '9012038010000000'
    type: REG_BINARY
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\Control Panel\Desktop'
    value: 'DragFullWindows'
    data: '1'
    type: REG_SZ
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\Control Panel\Desktop\WindowMetrics'
    value: 'MinAnimate'
    data: '0'
    type: REG_SZ
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ListviewAlphaSelect'
    data: '1'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'IconsOnly'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'TaskbarAnimations'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'ListviewShadow'
    data: '1'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects'
    value: 'VisualFXSetting'
    data: '3'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\DWM'
    value: 'EnableAeroPeek'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Windows\DWM'
    value: 'AlwaysHibernateThumbnails'
    data: '0'
    type: REG_DWORD
    
    
