---
title: Configure OEM Information
description: Configures OEM information to contain the Atlas version and the Atlas Discord server
actions:
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Manufacturer'
    data: 'Atlas Team'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'Model'
    data: 'AtlasOS v0.3.2'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportURL'
    data: 'https://discord.atlasos.net'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\OEMInformation'
    value: 'SupportPhone'
    data: 'https://github.com/Atlas-OS/Atlas'
    type: REG_SZ
  - !registryValue:
    path: 'HKLM\SOFTWARE\Atlas'
    value: 'WinreFallbackFixed'
    data: '1'
    type: REG_SZ
