---
title: Revert Tweaks from Old Versions
description: Reverts removed tweaks, so that people who upgrade from older Atlas versions no longer have the tweaks
actions:
    # Hide UWP Badges on Taskbar
    # Tweak was improperly titled, disables badges on all apps
    # Why would you disable badges on UWP apps anyways?
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced'
    value: 'TaskbarBadges'
    data: '1'
    type: REG_DWORD

    # Reverted for security reasons
    # Users get no update notifications otherwise, which means many users don't update at all
  - !cmd:
    command: 'reg import "AtlasDesktop\3. General Configuration\Windows Update\Update Notifications\Enable Update Notifications (default).reg"'
    exeDir: true
    wait: true

    # Revert deferring quality updates - these are secruity updates
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate', value: 'DeferQualityUpdates', operation: delete}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate', value: 'DeferQualityUpdatesPeriodInDays', operation: delete}

    # Revert network tweaks
    # ---------------------
    # Not worth it - https://devblogs.microsoft.com/oldnewthing/20061123-14/?p=28923
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched', value: 'NonBestEffortLimit', operation: delete}
    # Not proven to do anything
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched', value: 'TimerResolution', operation: delete}
    # Used for DSCP? DSCP is not relevant for home networks
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\QoS', value: 'Do not use NLA', operation: delete}
    # Revert CTCP
    # > "seen as very delay sensitive and also worked poorly in data centre"
    # > https://en.wikipedia.org/wiki/Compound_TCP#Windows_8_and_up
  - !cmd: {command: 'netsh int tcp set supplemental Internet congestionprovider=default'}
    # Revert disabling smart name resolution
    # Doesn't prevent DNS leakage, just makes it less optimised
  - !registryValue: {path: 'HKLM\SYSTEM\CurrentControlSet\Services\Dnscache\Parameters', value: 'DisableParallelAandAAAA', operation: delete}
  - !registryValue: {path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows NT\DNSClient', value: 'DisableSmartNameResolution', operation: delete}
