---
title: Optimize NTFS
description: Optimizes the NTFS filesystem for optimal QoL, performance and privacy
privilege: TrustedInstaller
actions:
    # https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/fsutil

    # Disable last access information on directories, performance/privacy
  - !run: {exe: 'fsutil', args: 'behavior set disablelastaccess 1'}

    # Disable the creation of 8.3 character-length file names on FAT- and NTFS-formatted volumes
    # https://ttcshelbyville.wordpress.com/2018/12/02/should-you-disable-8dot3-for-performance-and-security
  - !run: {exe: 'fsutil', args: 'behavior set disable8dot3 1'}
