blank_issues_enabled: false
contact_links:
  - name: General discussions
    url: https://discord.atlasos.net
    about: Please join our Discord server for general discussions.
  - name: General discussions (if you do not use Discord)
    url: https://forum.atlasos.net
    about: Use our forum for general discussions.
  - name: Contribute to Atlas Documentation
    url: https://github.com/Atlas-OS/docs
    about: Contribute to Atlas Documentation in this repository.
  - name: Report an issue (non-Atlas related issue)
    url: https://forum.atlasos.net
    about: Please report any non-Atlas related issue in our ``Bug Report`` section on our Forum (Website, Discord bot, etc.).
