---
title: Tweaks Root Playbook File
description: Runs all of the Atlas playbook tweaks
actions: []
tasks:
  # ------------------------- NOTES ------------------------- #

  # - Each root folder has its own AME Wizard status
  # - You can disable a certain YAML file by commenting it out
  # - The playbook files are ran in order
  # - Each root category is a root folder name
  # - Comments for the individual playbook files have no text
  #   length limit, although keep it reasonable

  # ----------------------- END NOTES ----------------------- #



  # -----------------------------------------------------
  #                      Networking
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # Tweaks for modifying network settings, which can lead
  # to improving network performance, security, etc.
  # -----------------------------------------------------
  - tweaks\statuses\status-networking.yml
  - tweaks\networking\disable-llmnr.yml
  - tweaks\networking\atlas-network-settings.yml

  # -------------------------------------------------------------------------- #
  #  networking\shares                                                         #
  # -------------------------------------------------------------------------- #
  - tweaks\networking\shares\restrict-anonymous-access.yml
  - tweaks\networking\shares\restrict-anonymous-enumeration.yml
  - tweaks\networking\shares\disable-smb-bandwidth-throttling.yml



  # -----------------------------------------------------
  #                      Performance
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # Tweaks for improving the performance of Windows, such as
  # responsiveness, latency, etc.
  # -----------------------------------------------------
  - tweaks\statuses\status-performance.yml
  - tweaks\performance\config-mmcss.yml
  - tweaks\performance\disable-auto-folder-discovery.yml
  # - tweaks\performance\disable-game-bar.yml
  - tweaks\performance\config-automatic-maintenance.yml
  - tweaks\performance\disable-background-apps.yml
  - tweaks\performance\disable-fth.yml
  - tweaks\performance\disable-sleep-study.yml

  # -------------------------------------------------------------------------- #
  #  performance\system                                                        #
  # -------------------------------------------------------------------------- #
  - tweaks\performance\system\config-boot-config.yml
  - tweaks\performance\system\disable-paging.yml
  - tweaks\performance\system\optimize-ntfs.yml
  - tweaks\performance\system\disable-service-host-split.yml
  - tweaks\performance\system\win32-priority-seperation.yml



  # -----------------------------------------------------
  #                        Privacy
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # Tweaks for disabling spying/tracking on Windows so
  # that you have more privacy.
  #
  # Also includes disabling features that are commonly
  # related to impacting privacy, like advertising.
  # -----------------------------------------------------
  - tweaks\statuses\status-privacy.yml
  - tweaks\privacy\config-app-permissions.yml
  - tweaks\privacy\config-windows-media-player.yml
  - tweaks\privacy\disable-activity-feed.yml
  - tweaks\privacy\disable-app-launch-tracking.yml
  - tweaks\privacy\disable-experimentation.yml
  - tweaks\privacy\disable-location-tracking.yml
  - tweaks\privacy\disable-lockscreen-camera.yml
  - tweaks\privacy\disable-online-speech-recognition.yml
  - tweaks\privacy\disable-pca.yml
  - tweaks\privacy\disable-perf-track.yml
  - tweaks\privacy\disable-privacy-experience.yml
  - tweaks\privacy\disable-device-monitoring.yml
  - tweaks\privacy\disable-rsop-logging.yml
  - tweaks\privacy\disable-speech-auto-updates.yml
  - tweaks\privacy\disable-tailored-experiences.yml
  - tweaks\privacy\disable-user-tracking.yml
  - tweaks\privacy\disable-web-lang-list-access.yml
  - tweaks\privacy\disable-win-error-reporting.yml
  - tweaks\privacy\disallow-ms-accounts.yml
  - tweaks\privacy\disallow-user-activity-upload.yml
  - tweaks\privacy\search-settings.yml

  # -------------------------------------------------------------------------- #
  #  privacy\advertising                                                       #
  # -------------------------------------------------------------------------- #
  - tweaks\privacy\advertising\disable-advertising-info.yml
  - tweaks\privacy\advertising\disable-bluetooth-advertising.yml
  - tweaks\privacy\advertising\disable-sync-provider-notifs.yml

  # -------------------------------------------------------------------------- #
  #  privacy\cloud                                                             #
  # -------------------------------------------------------------------------- #
  - tweaks\privacy\cloud\disable-setting-sync.yml
  - tweaks\privacy\cloud\disable-suggest-ways-to-finish-setup.yml
  - tweaks\privacy\cloud\disallow-message-cloud-sync.yml

  # -------------------------------------------------------------------------- #
  #  privacy\telemetry                                                         #
  # -------------------------------------------------------------------------- #
  - tweaks\privacy\telemetry\disable-activation-telemetry.yml
  - tweaks\privacy\telemetry\disable-ceip.yml
  - tweaks\privacy\telemetry\disable-diagnostic-tracing.yml
  - tweaks\privacy\telemetry\disable-dotnet-cli-telemetry.yml
  - tweaks\privacy\telemetry\disable-input-telemetry.yml
  - tweaks\privacy\telemetry\disallow-data-collection.yml



  # -----------------------------------------------------
  #                          QOL
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # QoL stands for Quality of Life, and are general
  # modifications designed for making Windows easier and
  # more pleasent to use for more advanced general users.
  #
  # QoL tweaks can be anything, but they are mostly to do
  # with modifying the graphical user interface (GUI).
  # -----------------------------------------------------
  - tweaks\statuses\status-qol.yml
  - tweaks\qol\best-wallpaper-quality.yml
  - tweaks\qol\config-start-menu.yml
  - tweaks\qol\config-windows-ink-workspace.yml
  - tweaks\qol\disable-background-auto-login.yml
  - tweaks\qol\disable-mouse-accel.yml
  - tweaks\qol\disable-settings-tips.yml
  - tweaks\qol\disable-spell-checking.yml
  - tweaks\qol\disable-store-auto-updates.yml
  - tweaks\qol\disable-touch-keyboard-features.yml
  - tweaks\qol\disable-touch-visual-feedback.yml
  - tweaks\qol\disable-usb-issues-notifications.yml
  - tweaks\qol\disable-windows-feedback.yml
  - tweaks\qol\disable-windows-spotlight.yml
  - tweaks\qol\do-not-reduce-sounds.yml
  - tweaks\qol\hide-disabled-disconnected-sounds.yml
  - tweaks\qol\show-all-tasks-control-panel.yml
  - tweaks\qol\visual-effects.yml
  - tweaks\qol\disable-tips.yml
  - tweaks\qol\disable-win11-settings-banner.yml

  # -------------------------------------------------------------------------- #
  #  qol\appearance                                                            #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\appearance\blue-tooltips.yml
  - tweaks\qol\appearance\atlas-theme.yml
  - tweaks\qol\appearance\disallow-theme-changes.yml

  # -------------------------------------------------------------------------- #
  #  qol\windows-update                                                        #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\windows-update\disable-nagging.yml
  - tweaks\qol\windows-update\disable-insider.yml
  - tweaks\qol\windows-update\disable-msrt-telemetry.yml
  - tweaks\qol\windows-update\disable-feature-updates.yml
  - tweaks\qol\windows-update\disable-auto-updates.yml
  - tweaks\qol\windows-update\disable-auto-reboot.yml
  - tweaks\qol\windows-update\disable-delivery-optimization.yml

  # -------------------------------------------------------------------------- #
  #  qol\ease-of-access                                                        #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\ease-of-access\disable-always-read-section.yml
  - tweaks\qol\ease-of-access\disable-annoying-features-shortcuts.yml
  - tweaks\qol\ease-of-access\disable-making-touch-easier.yml
  - tweaks\qol\ease-of-access\disable-warning-sounds.yml

  # -------------------------------------------------------------------------- #
  #  qol\explorer                                                              #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\explorer\always-more-details-transfer.yml
  - tweaks\qol\explorer\disable-invalid-shortcuts-search.yml
  - tweaks\qol\explorer\disable-check-boxes.yml
  - tweaks\qol\explorer\disable-folders-this-pc.yml
  - tweaks\qol\explorer\disable-network-navigation-pane.yml
  - tweaks\qol\explorer\disable-sharing-wizard.yml
  - tweaks\qol\explorer\full-context-on-more-than-15-items.yml
  - tweaks\qol\explorer\hide-frequently-used-items.yml
  - tweaks\qol\explorer\import-power-plan.yml
  - tweaks\qol\explorer\extend-cache.yml
  - tweaks\qol\explorer\minimize-mouse-hover-time.yml
  - tweaks\qol\explorer\no-internet-open-with.yml
  - tweaks\qol\explorer\open-to-this-pc.yml
  - tweaks\qol\explorer\removable-drives-only-this-pc.yml
  - tweaks\qol\explorer\remove-previous-versions.yml
  - tweaks\qol\explorer\remove-shortcut-text.yml
  - tweaks\qol\explorer\show-files.yml
  - tweaks\qol\explorer\classic-search.yml
  - tweaks\qol\explorer\dont-show-office-files.yml
  - tweaks\qol\explorer\use-compact-mode.yml
  - tweaks\qol\explorer\disable-gallery.yml
  - tweaks\qol\explorer\debloat-send-to.yml

  # -------------------------------------------------------------------------- #
  #  qol\explorer\add-context-menus                                            #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\explorer\add-context-menus\merge-as-trustedinstaller.yml
  - tweaks\qol\explorer\add-context-menus\new-bat.yml
  - tweaks\qol\explorer\add-context-menus\new-ps1.yml
  - tweaks\qol\explorer\add-context-menus\new-reg.yml

  # -------------------------------------------------------------------------- #
  #  qol\explorer\remove-context-menus                                         #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\explorer\remove-context-menus\cast-to-device.yml
  - tweaks\qol\explorer\remove-context-menus\extract-all.yml
  - tweaks\qol\explorer\remove-context-menus\give-access-to.yml
  - tweaks\qol\explorer\remove-context-menus\include-in-library.yml
  - tweaks\qol\explorer\remove-context-menus\new-bitmap.yml
  - tweaks\qol\explorer\remove-context-menus\new-rtf.yml
  - tweaks\qol\explorer\remove-context-menus\paint-3D.yml
  - tweaks\qol\explorer\remove-context-menus\share.yml
  - tweaks\qol\explorer\remove-context-menus\troubleshooting-compat.yml

  # -------------------------------------------------------------------------- #
  #  qol\security                                                              #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\security\disable-uac-secure-desktop.yml

  # -------------------------------------------------------------------------- #
  #  qol\shell                                                                 #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\shell\alt-tab-open-windows.yml
  - tweaks\qol\shell\config-autorun-autoplay.yml
  - tweaks\qol\shell\disable-aero-shake.yml
  - tweaks\qol\shell\disable-low-disk-warning.yml
  - tweaks\qol\shell\disable-menu-delay.yml
  - tweaks\qol\shell\disable-network-location-wizard.yml
  - tweaks\qol\shell\set-unpinned-notification-items.yml
  - tweaks\qol\shell\restore-old-context-menu.yml
  - tweaks\qol\shell\show-more-pins.yml
  - tweaks\qol\shell\no-recommendations-start-menu.yml
  - tweaks\qol\shell\disable-nearby-sharing.yml
  - tweaks\qol\shell\disallow-edge-swipe.yml

  # -------------------------------------------------------------------------- #
  #  qol\startup-shutdown                                                      #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\startup-shutdown\decrease-shutdown-time.yml
  - tweaks\qol\startup-shutdown\disable-startup-delay.yml
  - tweaks\qol\startup-shutdown\force-end-shutdown-apps.yml
  - tweaks\qol\startup-shutdown\enable-verbose-messages.yml

  # -------------------------------------------------------------------------- #
  #  qol\system                                                                #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\system\crash-control-qol.yml
  - tweaks\qol\system\disable-wpbt.yml

  # -------------------------------------------------------------------------- #
  #  qol\taskbar                                                               #
  # -------------------------------------------------------------------------- #
  - tweaks\qol\taskbar\cmd-win-x.yml
  - tweaks\qol\taskbar\disable-cloud-optimized-content.yml
  - tweaks\qol\taskbar\disable-desktop-peek.yml
  - tweaks\qol\taskbar\disable-news-and-interests.yml
  - tweaks\qol\taskbar\disable-tablet-mode.yml
  - tweaks\qol\taskbar\hide-meet-now.yml
  - tweaks\qol\taskbar\hide-task-view.yml
  - tweaks\qol\taskbar\config-pins.yml
  - tweaks\qol\taskbar\disable-copilot.yml
  - tweaks\qol\taskbar\disable-windows-chat.yml
  - tweaks\qol\taskbar\set-to-left.yml
  - tweaks\qol\taskbar\end-task.yml



  # -----------------------------------------------------
  #                       Security
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # These tweaks aim to enhance Windows' security, upon
  # its defaults.
  # -----------------------------------------------------
  - tweaks\statuses\status-security.yml
  - tweaks\security\block-anonymous-enum-sam.yml
  - tweaks\security\delete-defaultuser0.yml
  - tweaks\security\disable-remote-assistance.yml



  # -----------------------------------------------------
  #                        Debloat
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # Tweaks for debloating Windows, which could be for
  # storage space or convienience.
  # -----------------------------------------------------
  - tweaks\statuses\status-debloat.yml
  - tweaks\debloat\config-content-delivery.yml
  - tweaks\debloat\disable-reserved-storage.yml
  - tweaks\debloat\disable-scheduled-tasks.yml
  - tweaks\debloat\hide-unused-security-pages.yml
  - tweaks\debloat\config-storage-sense.yml



  # -----------------------------------------------------
  #                        Scripts
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # These are playbook files that run external PowerShell
  # or batch scripts for more advanced operations.
  # -----------------------------------------------------
  - tweaks\statuses\status-scripts.yml
  - tweaks\scripts\script-file-associations.yml
  - tweaks\scripts\script-core-isolation.yml
  - tweaks\scripts\script-mitigations.yml
  - tweaks\scripts\script-devices.yml
  - tweaks\scripts\script-pfp.yml
  - tweaks\scripts\script-finalize.yml
  - tweaks\scripts\script-backup2.yml
  - tweaks\scripts\script-clientcbs.yml



  # -----------------------------------------------------
  #                         Misc
  # -----------------------------------------------------
  # >>> Description <<<
  #
  # Miscellaneous tweaks which do not fit into other
  # categories.
  # -----------------------------------------------------
  - tweaks\statuses\status-misc.yml
  - tweaks\misc\config-time.yml
  - tweaks\misc\delete-windows-specific-files.yml
  - tweaks\misc\config-oem-information.yml
  - tweaks\misc\rebuild-perf-counters.yml
  - tweaks\misc\create-shortcuts.yml
  - tweaks\misc\add-music-videos-to-home.yml
  - tweaks\misc\add-newUsers-script.yml
  - tweaks\scripts\script-power.yml # Done last on purpose
  - tweaks\misc\enable-notifications.yml
