---
title: Configure Paging Settings
description: Configures memory paging settings for the best performance
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
    value: 'DisablePagingExecutive'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SYSTEM\CurrentControlSet\Control\Session Manager\Memory Management'
    value: 'DisablePageCombining'
    data: '1'
    type: REG_DWORD
