---
title: Configure Taskbar Pins
description: Configures taskbar pins for QoL, puts the browser first (if there is one) and Explorer next
privilege: TrustedInstaller
actions:
    # PowerShell commands used:
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "FavoritesResolve").FavoritesResolve) -replace '-'
    # [BitConverter]::ToString($(Get-ItemProperty -Path "HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Taskband" -Name "Favorites").Favorites) -replace '-'

  - !run:
    exe: 'TASKBARPINS.cmd'
    exeDir: true
    wait: true
  - !run:
    exe: 'TASKBARPINS.cmd'
    args: '"Brave"'
    option: 'browser-brave'
    exeDir: true
    wait: true
  - !run:
    exe: 'TASKBARPINS.cmd'
    args: '"LibreWolf"'
    option: 'browser-librewolf'
    exeDir: true
    wait: true
  - !run:
    exe: 'TASKBARPINS.cmd'
    args: '"Google Chrome"'
    option: 'browser-chrome'
    exeDir: true
    wait: true
