---
title: Never Use Tablet Mode
description: Makes Windows never use tablet mode for QoL
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\ImmersiveShell'
    value: 'SignInMode'
    data: '1'
    type: REG_DWORD
    
    
