---
title: Add 'End task' to the taskbar
description: Adds 'End task' as a right-click option on taskbar for QoL
builds: [ '>22000' ]
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Advanced\TaskbarDeveloperSettings'
    value: 'TaskbarEndTask'
    data: '1'
    type: REG_DWORD
    
    
