---
title: Force Close Applications On Session End
description: Forcefully closes all applications on restart, shut down, or sign out of Windows, instead of prompting the user to save everything first
actions:
  - !registryValue:
    path: 'HKU\AME_UserHive_Default\Control Panel\Desktop'
    value: 'AutoEndTasks'
    data: '1'
    type: REG_SZ
    
    
