---
title: Disable 'Always Read and Scan This Section'
description: Disables 'Always Read and Scan This Section' in Control Panel for QoL
actions:
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Ease of Access'
    value: 'selfscan'
    data: '0'
    type: REG_DWORD
    
    
  - !registryValue:
    path: 'HKU\DefaultUser\SOFTWARE\Microsoft\Ease of Access'
    value: 'selfvoice'
    data: '0'
    type: REG_DWORD
    
    
