---
title: Configure Search on the Taskbar
description: Configures search for the optimal usability and privacy, such as disabling online features to make it simplistic and usable
privilege: TrustedInstaller
actions:
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'
    value: 'BingSearchEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsAADCloudSearchEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsDeviceSearchHistoryEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'IsMSACloudSearchEnabled'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings'
    value: 'SafeSearchMode'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'ConnectedSearchUseWeb'
    data: '0'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'DisableWebSearch'
    data: '1'
    type: REG_DWORD
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Search'
    value: 'EnableDynamicContentInWSB'
    data: '0'
    type: REG_DWORD
    
    # Disable online search and don't include web results from Bing
  - !registryValue:
    path: 'HKCU\SOFTWARE\Policies\Microsoft\Windows\Explorer'
    value: 'DisableSearchBoxSuggestions'
    data: '1'
    type: REG_DWORD
    
    # Set search as icon on taskbar
  - !registryValue:
    path: 'HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Search'
    value: 'SearchboxTaskbarMode'
    data: '1'
    type: REG_DWORD
