---
title: Applies Atlas' Network Settings
description: Applies Atlas' optimised network settings
actions:
  - !cmd:
    command: '"AtlasDesktop\8. Troubleshooting\Network\Reset Network to Atlas Default.cmd" /silent'
    exeDir: true
    wait: true
    runas: currentUserElevated
