---
title: Configure Packet Scheduler Timer Resolution
description: Configures the network stack (packet scheduler) timer resolution to be more precise
actions:
  # https://admx.help/?Category=Windows_11_2022&Policy=Microsoft.Policies.QualityofService::QosTimerResolution
  - !registryValue:
    path: 'HKLM\SOFTWARE\Policies\Microsoft\Windows\Psched'
    value: 'TimerResolution'
    data: '1'
    type: REG_DWORD
